// This file was generated by the Zuplo CLI migrate-dev-portal command.
// It is used to configure the Zuplo dev portal.
// You can edit this file to customize the dev portal.
// For more information, see https://zuplo.com/docs/dev-portal/zudoku/configuration/overview
import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  basePath: "/docs",
  site: {
    logo: {
      src: {
        light: "https://cdn.zuplo.com/assets/50a9c235-65e3-4a88-8c86-dc023196476f.png",
        dark: "https://cdn.zuplo.com/assets/50a9c235-65e3-4a88-8c86-dc023196476f.png"
      },
      alt: "Rick and Morty API (by Zuplo)",
      href: "/"
    },
    title: "Rick and Morty API (by Zuplo)"
  },
  metadata: {
    favicon:
      "https://cdn.zuplo.com/assets/50a9c235-65e3-4a88-8c86-dc023196476f.png",
    title: "Rick and Morty API (by Zuplo)",
  },
  navigation: [
    {
      type: "doc",
      file: "index",
      label: "Home",
      path: "/"
    },
    {
      type: "link",
      to: "/api",
      label: "API Reference",
    },
  ],
  apis: [
    {
      type: "file",
      input: "../config/routes.oas.json",
      path: "/api",
    },
  ],
  authentication: {
    type: "auth0",
    clientId: "v0cOpST3pX6NIs1VGLVvNjaN3mSBomKk",
    domain: "zuplo-samples.us.auth0.com",
    audience: "https://api.example.com/",
  },
};
export default config;
